In [19]:
import numpy as np
from nptyping import NDArray

In [30]:
l1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
l2 = np.array(2)
l2

array(2)

# DIMENSION IN NUMPY


0D = Scalar
1D = Vector
2D = Matrix
3D, 4D, 5D = Tensor


In [17]:
# 1 DIMENSIONAL ARRAY

l1: NDArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.int64)
print("Shape", l1.shape)
print(f"Size {l1.size}")
print(f"Item Size {l1.itemsize}")
print(f"Memory Address {l1.data}")
print(f"Data Type {l1.dtype}")

Shape (9,)
Size 9
Item Size 8
Memory Address <memory at 0x000002CAEF207AC0>
Data Type int64


In [13]:
# 2 DIMENSIONAL ARRAY

l1: NDArray = np.array([[1, 2, 3, 4, 5, 6,],
                        [7, 8, 9, 10, 11, 12],
                        [7, 8, 9, 10, 11, 12]])

print("Shape", l1.shape)
print(f"Size {l1.size}")
print(f"Item Size {l1.itemsize}")
print(f"Memory Address {l1.data}")
print(f"Data Type {l1.dtype}")
print(f"Dimension {l1.ndim}")

Shape (3, 6)
Size 18
Item Size 4
Memory Address <memory at 0x000002CAEF32A0C0>
Data Type int32
Dimension 2


In [16]:
# 3 DIMENSIONAL ARRAY

l1: NDArray = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]]
])

print("Shape", l1.shape)
print(f"Size {l1.size}")
print(f"Item Size {l1.itemsize}")
print(f"Memory Address {l1.data}")
print(f"Data Type {l1.dtype}")
print(f"Dimension {l1.ndim}")

Shape (2, 2, 3)
Size 12
Item Size 4
Memory Address <memory at 0x000002CAE7D32D40>
Data Type int32
Dimension 3


In [26]:
list1: NDArray = np.arange(1, 13)
list1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
list2: NDArray = list1.reshape((3, 3))
list2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
list2: NDArray = list1.reshape((2, 2, 3))
list2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## MATH OPERATION IN NUMPY

In [32]:
py_list = [1 , 2, 3, 4]
py_list + 5

TypeError: can only concatenate list (not "int") to list

In [38]:
# np_list = np.arange(1, 13)
np_list = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
# np_list + 6
np.add(np_list, 5)

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
# np_list *2
np.multiply(np_list, 2)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

## METHODS IN NUMPY

In [41]:
my_list : NDArray = np.array([1, 2, 3, 4, 5])
my_list.min()
my_list.max()

5

In [43]:
my_list = np.ones((1,2,3), dtype=int)
my_list

array([[[1, 1, 1],
        [1, 1, 1]]])